### ISSUE TITLE
我用官方的例程，为什么无法和模块通讯？

### ISSUE THREAD

**Issue by liantianji** [BlackRain543/Cat-rice-dryer#1]
你好，我用官方的USART例程，为什么无法和模块通讯？复制了你的代码过来也是无法通讯~

**Comment by BlackRain543** [comment]
有用涂鸦通讯助手调试吗，看看是MPU的问题还是涂鸦模块的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BlackRain543/Cat-rice-dryer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 下午2:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[BlackRain543/Cat-rice-dryer] 我用官方的例程，为什么无法和模块通讯？ (#1)





 
你好，我用官方的USART例程，为什么无法和模块通讯？复制了你的代码过来也是无法通讯~

**Comment by liantianji** [comment]
我把TTL焊在模块上，用调试助手没问题。可以正常通讯。之前都是用stm32f103的想换个便宜的mcu，居然翻车了。

原理图在这硬件应该没什么问题 
 https://oshwhub.com/idaniel/hang-shunmcu-wang-lao-qie-huan-qi_copy

**Comment by BlackRain543** [comment]
无法通讯的可能问题有很多，具体是什么现象，是怎么判断出来的呢？有写一些简单的程序判断通讯问题没？MCU的通讯和涂鸦模块都没问题吗？两个都要调试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月31日(星期六) 下午2:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BlackRain543/Cat-rice-dryer] 我用官方的例程，为什么无法和模块通讯？ (#1)





 
我把TTL焊在模块上，用调试助手没问题。可以正常通讯。之前都是用stm32f103的想换个便宜的mcu，居然翻车了。
 
原理图在这硬件应该没什么问题
 https://oshwhub.com/idaniel/hang-shunmcu-wang-lao-qie-huan-qi_copy

**Comment by liantianji** [comment]
刚入门新手不知道，有办法判断usart初始化后是正常状态还是其它状态。

**Comment by BlackRain543** [comment]
加个QQ吧先




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月31日(星期六) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BlackRain543/Cat-rice-dryer] 我用官方的例程，为什么无法和模块通讯？ (#1)





 
刚入门新手不知道，有办法判断usart初始化后是正常状态还是其它状态。

**Comment by liantianji** [comment]
你qq号多少，我加你。

**Comment by BlackRain543** [comment]
893023158




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月31日(星期六) 下午2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BlackRain543/Cat-rice-dryer] 我用官方的例程，为什么无法和模块通讯？ (#1)





 
你qq号多少，我加你。
